

const images = [ 
  require('./1.jpeg'),
  require('./2.jpeg'),
  require('./3.jpeg'),
  require('./4.jpeg'),
  require('./5.jpeg'),
  require('./6.jpeg'),
  require('./7.jpeg'),
  require('./8.jpeg'),
  require('./9.jpeg'),
  require('./10.jpeg'),
  require('./11.jpeg'),
  require('./12.jpeg'),
  require('./13.jpeg'),
  require('./14.jpeg'),
  require('./15.jpeg'),
  require('./16.jpeg'),
  require('./17.jpeg'),
  require('./18.jpeg'),
  require('./19.jpeg'),
  require('./20.jpeg'),
  require('./21.jpeg'),
  require('./22.jpeg'),
  require('./23.jpeg'),
  require('./24.jpeg'),
  require('./25.jpeg'),
  require('./26.jpeg'),
  require('./27.jpeg'),
  require('./28.jpeg'),
  require('./29.jpeg'),
  require('./30.jpeg'),
  require('./31.jpeg'),
  require('./32.jpeg'),
  require('./33.jpeg'),
  require('./34.jpeg'),
  require('./35.jpeg'),
  require('./36.jpeg'),
  require('./37.jpeg'),
  require('./38.jpeg'),
  require('./39.jpeg'),
  require('./40.jpeg'),
  require('./41.jpeg'),
  require('./42.jpeg'),
  require('./43.jpeg'),
  require('./44.jpeg'),
  require('./45.jpeg'),
  require('./46.jpeg'),
  require('./47.jpeg'),
  require('./48.jpeg'),
  require('./49.jpeg'),
  require('./50.jpeg'),
  require('./51.jpeg'),
  require('./52.jpeg'),
  require('./53.jpeg'),
  require('./54.jpeg'),
  require('./55.jpeg'),
  require('./56.jpeg'),
  require('./57.jpeg'),
  require('./58.jpeg'),
]


  export default images;