const comedyJokes = [
    "Why don't scientists trust atoms? Because they make up everything!",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "How do you organize a space party? You 'planet'!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I used to play piano by ear, but now I use my hands.",
    "I'm on a seafood diet. I see food, and I eat it.",
    "What do you get if you cross a snowman and a vampire? Frostbite!",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "I asked the librarian if they had books on paranoia. She whispered, 'They're right behind you!'",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "I told my computer I needed a break, and now it won't stop sending me 'Get well soon' cards.",
    "Why did the math book look sad? Because it had too many problems.",
    "I used to be a baker, but I couldn't make enough dough.",
    "I couldn't figure out how to put my seatbelt on. Then it just 'clicked'!",
    "I'm writing a book on reverse psychology. Please don't read it!",
    "I used to play piano by ear, but now I use my hands.",
    "I'm friends with all electricians. We have such great current connections.",
    "I'm so good at sleeping; I can do it with my eyes closed.",
    "I'm on a whiskey diet. I've lost three days already!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why was the math book sad? Because it had too many problems.",
    "I couldn't figure out how to put my seatbelt on. Then it just 'clicked'!",
    "My wife told me I should do lunges to stay in shape. That was a big step forward.",
    "I'm friends with all electricians. We have such great current connections.",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "I'm so good at sleeping, I can do it with my eyes closed.",
    "I'm on a seafood diet. I see food, and I eat it.",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "I asked the librarian if they had books on paranoia. She whispered, 'They're right behind you!'",
    "I'm writing a book on reverse psychology. Please don't read it!",
    "I used to be a baker, but I couldn't make enough dough.",
    "I'm on a whiskey diet. I've lost three days already!",
    "I'm so good at sleeping; I can do it with my eyes closed.",
    "I used to play piano by ear, but now I use my hands.",
    "I'm friends with all electricians. We have such great current connections.",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "I'm on a seafood diet. I see food, and I eat it.",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "I asked the librarian if they had books on paranoia. She whispered, 'They're right behind you!'",
    "I'm writing a book on reverse psychology. Please don't read it!",
    "I used to be a baker, but I couldn't make enough dough.",
    "I'm on a whiskey diet. I've lost three days already!",
    "I'm so good at sleeping; I can do it with my eyes closed.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  ];

  export default comedyJokes;