const quotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "In the middle of every difficulty lies opportunity. - Albert Einstein",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "The best revenge is massive success. - Frank Sinatra",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "The biggest risk is not taking any risk. In a world that's changing quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. - Steve Jobs",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "I have learned over the years that when one's mind is made up, this diminishes fear. - Rosa Parks",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "Action is the foundational key to all success. - Pablo Picasso",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "The biggest risk is not taking any risk. In a world that's changing quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. - Steve Jobs",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "Action is the foundational key to all success. - Pablo Picasso",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "The biggest risk is not taking any risk. In a world that's changing quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. - Steve Jobs",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "Action is the foundational key to all success. - Pablo Picasso",
  ];


  export default quotes;